title: Sidhant Kumar
description: "Sidhant Kumar's personal website — homelab blogging, projects, and experience."
url: "https://sidhantkumar0.github.io"
baseurl: "/Sidhants-Homelab"

remote_theme: chesterhow/tale

author:
  name: Sidhant Kumar
  url: https://github.com/sidhantkumar0
  email: sidhantkumar1001@gmail.com

markdown: kramdown

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

permalink: /:year-:month-:day/:title
